added tests for KSV003, KSV011 and KSV015 general rules (part1)
aquasecurity/appshield pull request #114
Opened 2021-07-09 15:29 UTC by AndreyLevchenko

2021-07-18 15:39 UTC, yoavrotems requested changes
Looks good just change functions names

2021-07-18 15:39 UTC, yoavrotems commented on kubernetes/policies/general/CPU_not_limited_test.rego
> +test_denied {
test_CPU_not_limited_denied

2021-07-18 15:39 UTC, yoavrotems commented on kubernetes/policies/general/CPU_not_limited_test.rego
> +test_allowed {
test_CPU_limited_allowed

2021-07-18 15:39 UTC, yoavrotems commented on kubernetes/policies/general/CPU_requests_not_specified_test.rego
> +test_denied {
test_CPU_requests_not_specified_denied

2021-07-18 15:39 UTC, yoavrotems commented on kubernetes/policies/general/CPU_requests_not_specified_test.rego
> +test_allowed {
test_CPU_requests_specified_allowed

2021-07-18 15:39 UTC, yoavrotems commented on kubernetes/policies/general/capabilities_no_drop_all_test.rego
> +test_denied {
test_cap_no_drop_all_denied

2021-07-18 15:39 UTC, yoavrotems commented on kubernetes/policies/general/capabilities_no_drop_all_test.rego
> +test_allowed {
test_cap_drop_all_allowed

2021-07-19 08:09 UTC, AndreyLevchenko commented
Hi @yoavrotems 
Thank you for suggestions. I've added changes requested

2021-07-19 13:58 UTC, yoavrotems approved these changes
LGTM

2021-07-19 13:58 UTC, merged