Add deprecated api version policy
aquasecurity/appshield pull request #80
Opened 2021-07-01 09:37 UTC by yoavrotems

2021-07-07 11:58 UTC, itaysk requested changes

2021-07-07 11:58 UTC, itaysk commented on kubernetes/policies/general/deprecated_api_version.rego
> +	allContainers := kubernetes.containers[_]
containers is not relevant in this policy. some resources doesn't have containers

2021-07-07 11:58 UTC, itaysk commented on kubernetes/policies/general/deprecated_api_version.rego
> +getDeprecatedApi[name] {
style comment: rules shouldn't start with "get"

2021-07-07 12:03 UTC, itaysk reviewed
metadata comments

2021-07-07 12:03 UTC, itaysk commented on kubernetes/policies/general/deprecated_api_version.rego
> +	"title": "Using A Deprecated API Version",
```suggestion
	"title": "Resource is using A deprecated API version",
```

2021-07-07 12:03 UTC, itaysk commented on kubernetes/policies/general/deprecated_api_version.rego
> +	"recommended_actions": "Don't use deprecated API versions",
```suggestion
	"recommended_actions": "Update to use a newer API version.",
```

2021-07-07 12:03 UTC, itaysk commented on kubernetes/policies/general/deprecated_api_version.rego
> +__rego_metadata__ := {
missing __rego_input__

2021-07-07 12:06 UTC, itaysk commented on kubernetes/policies/general/deprecated_api_version.rego
> +	"severity": "Critical",
I don't think this is a Critical severity policy

2021-07-07 12:23 UTC, itaysk reviewed
General comment, I find this policy a bit odd because it's highly dependent on the kubernetes version that the customer is intending to deploy the resource at, and we don't have this information. for example, we might recommend to update to apps/v1, but this version is unsupported on the customer's cluster. If we do intend to keep this policy, we should thoroughly include all the version changes that are listed here: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#removed-apis-by-release

2021-07-07 15:37 UTC, itaysk approved these changes
LGTM, consider changing the severity to low

2021-07-07 15:53 UTC, knqyf263 commented
Thanks. I'll take a look at last.

2021-09-14 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/appshield?pullRequest=80) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/appshield?pullRequest=80) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/appshield?pullRequest=80) it.</sub>

2022-02-07 16:47 UTC, merged